#!/bin/bash
# Structure TODO generator/updater.
#
# Scans each service's src/ tree and writes a checklist section into that
# service's TODO.md: `[ ]` for empty stub files, `[x]` for files that have
# content. Re-running updates the section in place (between the markers
# below) instead of duplicating it, so it's safe to run after every scaffold
# change to keep TODO.md in sync with what's actually on disk.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICES=("data-pipeline" "forecast-api")

START_MARKER="<!-- STRUCTURE:START (auto-generated by services/scripts/update_structure_todos.sh — do not edit by hand) -->"
END_MARKER="<!-- STRUCTURE:END -->"

for svc in "${SERVICES[@]}"; do
    SVC_DIR="$ROOT_DIR/$svc"
    SRC_DIR="$SVC_DIR/src"
    TODO_FILE="$SVC_DIR/TODO.md"

    if [ ! -d "$SRC_DIR" ]; then
        echo "⚠️  Skipping $svc: no src/ directory yet (nothing scaffolded)."
        continue
    fi
    if [ ! -f "$TODO_FILE" ]; then
        echo "⚠️  Skipping $svc: no TODO.md found at $TODO_FILE."
        continue
    fi

    echo "🔍 Scanning $svc structure..."

    BODY_FILE=$(mktemp)
    {
        echo "$START_MARKER"
        echo "### 🗂 Structure"
        echo
        echo "_Auto-generated by \`services/scripts/update_structure_todos.sh\`. \`[ ]\` = empty stub file, \`[x]\` = has content. Re-run after adding/removing files to keep this current — do not hand-edit between the markers._"
        echo
        while IFS= read -r -d '' file; do
            rel="${file#"$SVC_DIR"/}"
            if [ -s "$file" ]; then
                mark="x"
            else
                mark=" "
            fi
            echo "- [$mark] \`$rel\`"
        done < <(find "$SRC_DIR" -type f -not -path "*/__pycache__/*" -not -name "*.pyc" -print0 | sort -z)
        echo "$END_MARKER"
    } >"$BODY_FILE"

    if grep -qF "$START_MARKER" "$TODO_FILE"; then
        awk -v start="$START_MARKER" -v end="$END_MARKER" -v bodyfile="$BODY_FILE" '
            $0 == start {
                while ((getline line < bodyfile) > 0) print line
                skip = 1
                next
            }
            $0 == end { skip = 0; next }
            skip { next }
            { print }
        ' "$TODO_FILE" >"$TODO_FILE.tmp" && mv "$TODO_FILE.tmp" "$TODO_FILE"
        echo "   Updated structure section in $TODO_FILE"
    else
        {
            echo
            cat "$BODY_FILE"
        } >>"$TODO_FILE"
        echo "   Added structure section to $TODO_FILE"
    fi

    rm -f "$BODY_FILE"
done

echo "✅ Structure TODOs synced."
