# Generated by notebooks/feature_validation_standalone.ipynb -- paste into
# ecolens.forecasting.features.FEATURE_COLUMNS (data-pipeline) and its
# structural duplicate in forecast-api's forecasting/features.py.
# Order matters: must match exactly between both copies.
SELECTED_FEATURE_COLUMNS: tuple[str, ...] = (
    "demand_mw",
    "dow_cos",
    "hour_cos",
    "hour_sin",
    "total_generation_mw",
    "temp_c",
    "pressure_hpa",
    "dew_point_c",
    "wind_direction_deg",
    "dow_sin",
    "price_mwh",
    "apparent_temp_c",
    "net_import_mw",
    "wind_gust_kmh",
    "wind_speed_kmh",
    "humidity_pct",
    "cloud_cover_pct",
    "renewable_proportion",
    "month_sin",
    "month_cos",
    "is_holiday",
    "renewable_generation_mw",
)
